Added more content

diff --git a/17.0/s2i/bin/assemble b/17.0/s2i/bin/assemble
--- a/17.0/s2i/bin/assemble
+++ b/17.0/s2i/bin/assemble
@@ -29,93 +29,6 @@ function getscanconfig() {
   done
 }
 
-# Verify that the deployment scanner has finished running
-function waitondeployments() {
-  if ! ismgmtup; then
-    echo "Timed out waiting for management listening port"
-    echo "Could not connect to JBoss management interface, skipping deployment verification"
-  else
-    SCANCONFIG=""
-    c=0
-    while [ "$SCANCONFIG" == "" ] && [ $c -lt 5 ]; do
-      getscanconfig
-      if [ "$SCANCONFIG" != "" ]; then
-        break
-      fi
-      sleep 2
-      let c=c+1
-    done
-
-    if [ "$SCANCONFIG" == "" ]; then
-      echo "Could not connect to JBoss management interface, skipping deployment verification"
-    elif [[ $SCANCONFIG =~ '"scan-enabled" => true' ]]; then
-      DEPLOYMENTS_DIR=/wildfly/standalone/deployments
-      pushd $DEPLOYMENTS_DIR
-
-      artifacts=()
-
-      while read -r -d $'\0'; do
-        artifacts+=("$REPLY")
-      done < <(find . -iregex '.*\.\([ejrsw]ar\|zip\)$' -print0)
-
-      deployexploded=false
-      if [[ $SCANCONFIG =~ '"auto-deploy-exploded" => true' ]]; then
-        deployexploded=true
-      fi
-      deployarchive=false
-      if [[ $SCANCONFIG =~ '"auto-deploy-zipped" => true' ]]; then
-        deployarchive=true
-      fi
-
-      artifactsdeployed=()
-      artifactsfailed=()
-      artifactsskipped=()
-      artifactsunknown=()
-      for artifact in ${artifacts[*]}; do
-        if ( [ -f $artifact ] && $deployarchive ) || ( [ -d $artifact ] && $deployexploded ); then
-          # TODO triple check this logic, add a timeout
-          while [[ -f ${artifact}.isdeploying || -f ${artifact}.pending ]]; do
-            echo "Artifact: ${artifact} is still deploying"
-            sleep 10
-          done
-
-          if [ -f ${artifact}.deployed ]; then
-            artifactsdeployed+=($artifact)
-          elif [ -f ${artifact}.failed ]; then
-            artifactsfailed+=($artifact)
-          else
-            artifactsunknown+=($artifact)
-          fi
-
-        else
-          # artifact skipped because of deployment scanner config
-          artifactsskipped+=($artifact)
-        fi
-      done
-
-      popd
-
-      if [ ${#artifactsskipped[@]} -gt 0 ]; then
-        echo "Artifacts skipped because of deployment-scanner configuration: ${artifactsskipped[*]}"
-      fi
-
-      if [ ${#artifactsfailed[@]} -gt 0 ]; then
-        echo "Failed deployments: ${artifactsfailed[*]}"
-        return 1
-      fi
-
-      if [ ${#artifactsdeployed[@]} -gt 0 ]; then
-        echo "Artifacts deployed: ${artifactsdeployed[*]}"
-      fi
-
-      if [ ${#artifactsunknown[@]} -gt 0 ]; then
-        echo "Artifacts in an unknown state: ${artifactsunknown[*]}"
-      fi
-    else
-      echo "Deployment scanner disabled, skipping deployment verification"
-    fi
-  fi
-}
 
 # Check if the server http port is up
 function ishttpup() {
@@ -231,9 +144,9 @@ function move_artifacts() {
 ADMIN=admin
 PASSWORD=passw0rd_
 
-# Source code provided to S2I is at ${HOME}
 LOCAL_SOURCE_DIR=${HOME}
 mkdir -p $LOCAL_SOURCE_DIR
+
 
 # the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
 # artifacts (*.war, *.jar)
@@ -271,9 +184,14 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
 
   pushd $LOCAL_SOURCE_DIR &> /dev/null
   JAVA_HOME=/etc/alternatives/java_sdk
-
-  if [ -z "$MAVEN_ARGS" ]; then
-    export MAVEN_ARGS="package -Popenshift -DskipTests -B"
+  if [ ! -z "${GALLEON_BUILD}" ]; then
+    if [ -z "$MAVEN_ARGS" ]; then
+        export MAVEN_ARGS="install -DskipTests -B"
+    fi
+  else
+    if [ -z "$MAVEN_ARGS" ]; then
+        export MAVEN_ARGS="package -Popenshift -DskipTests -B"
+    fi
   fi
 
   # If MAVEN_SETTINGS specified will always add to MAVEN_ARGS
@@ -332,39 +250,51 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
     echo "Aborting due to error code $ERR from mvn package"
     exit $ERR
   fi
-
-  echo "Moving built war files into $DEPLOY_DIR for later deployment..."
+  if [ ! -z "${GALLEON_BUILD}" ]; then
+    echo "Moving provisioned server to output directory"
+  else
+    echo "Moving built war files into $DEPLOY_DIR for later deployment..."
+  fi
   popd &> /dev/null
 else
   echo "Moving binaries in source directory into $DEPLOY_DIR for later deployment..."
   move_artifacts "." war ear rar jar
 fi
 
-# Move built artifacts (if any!) from the target/ directory
-# (or $ARTIFACT_DIR if specified)
-if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR ]; then
-  move_artifacts "$ARTIFACT_DIR" war ear rar jar
-fi
+if [ ! -z "${GALLEON_BUILD}" ]; then
+   if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly ]; then
+      cp -r $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly /output/wildfly
+   else
+      echo "Error, no wildfly server provisioned in $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly"
+      exit 1
+   fi
+else
+    # Move built artifacts (if any!) from the target/ directory
+    # (or $ARTIFACT_DIR if specified)
+    if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR ]; then
+      move_artifacts "$ARTIFACT_DIR" war ear rar jar
+    fi
 
-if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
-  move_artifacts "deployments" war ear rar jar
-fi
+    if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
+      move_artifacts "deployments" war ear rar jar
+    fi
 
-if [ -d $LOCAL_SOURCE_DIR/cfg ]; then
-  echo "Copying config files from project..."
-  cp cfg/* /wildfly/standalone/configuration
-  chgrp -R 0 /wildfly/standalone/configuration
-  chmod -R g+rw /wildfly/standalone/configuration
-fi
+    if [ -d $LOCAL_SOURCE_DIR/cfg ]; then
+      echo "Copying config files from project..."
+      cp cfg/* /wildfly/standalone/configuration
+      chgrp -R 0 /wildfly/standalone/configuration
+      chmod -R g+rw /wildfly/standalone/configuration
+    fi
 
-# this dir needs to always exist because the extended build
-# flow expects to copy from it (even if it's empty)
-mkdir /wildfly/provided_modules
-if [ -d $LOCAL_SOURCE_DIR/modules ]; then
-  echo "Copying modules from project..."
-  cp -r modules/* /wildfly/provided_modules
-  chgrp -R 0 /wildfly/provided_modules
-  chmod -R g+rw /wildfly/provided_modules
+    # this dir needs to always exist because the extended build
+    # flow expects to copy from it (even if it's empty)
+    mkdir /wildfly/provided_modules
+    if [ -d $LOCAL_SOURCE_DIR/modules ]; then
+      echo "Copying modules from project..."
+      cp -r modules/* /wildfly/provided_modules
+      chgrp -R 0 /wildfly/provided_modules
+      chmod -R g+rw /wildfly/provided_modules
+    fi
 fi
 echo "...done"
 
