Git retrieval of galleon descriptions

diff --git a/17.0/s2i/bin/assemble b/17.0/s2i/bin/assemble
--- a/17.0/s2i/bin/assemble
+++ b/17.0/s2i/bin/assemble
@@ -186,6 +186,32 @@ cp -Rf /opt/s2i/destination/src/. $LOCAL_SOURCE_DIR
 chgrp -R 0 $LOCAL_SOURCE_DIR
 chmod -R g+rw $LOCAL_SOURCE_DIR
 
+if [ ! -z "$GALLEON_GIT_URL" ]; then
+   GIT="git clone --depth=1"
+   if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
+     echo "Replacing existing Galleon description in $GALLEON_LOCAL_PROVISIONING with $GALLEON_GIT_URL"
+     rm -r $GALLEON_LOCAL_PROVISIONING
+   fi
+   if [ ! -z "$GALLEON_GIT_BRANCH" ]; then
+     GIT="$GIT -b $GALLEON_GIT_BRANCH"
+   fi
+   systime=`date +%s`
+   gitDir=/tmp/galleon-repo-$systime
+   if [ -z "$GALLEON_GIT_CONTEXT_DIR" ]; then
+     GALLEON_GIT_CONTEXT_DIR=""
+   fi
+   echo "Cloning galleon description project $GIT $GALLEON_GIT_URL"
+   $GIT $GALLEON_GIT_URL $gitDir
+   GIT_ERR=$?
+   if [ $GIT_ERR -ne 0 ]; then
+     echo "Aborting due to error code $ERR from $GIT $GALLEON_URL"
+     exit $GIT_ERR
+   fi
+   mv $gitDir/$GALLEON_GIT_CONTEXT_DIR $GALLEON_LOCAL_PROVISIONING
+   rm -r $gitDir
+fi
+
+
 if [ -d $LOCAL_SOURCE_DIR/configuration ]; then
   echo "Copying config files from project..."
 
@@ -209,20 +235,12 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
 
   pushd $LOCAL_SOURCE_DIR &> /dev/null
   JAVA_HOME=/etc/alternatives/java_sdk
-  GALLEON_DEFAULT_ARGS="install -DskipTests -B"
-  # When doing a Galleon build, MAVEN_ARGS are re-used.
-  # If galleon build done with app, could have a need to separate args.
-  if [ ! -z "${GALLEON_BUILD}" ]; then
-    if [ -z "$MAVEN_ARGS" ]; then
-        export MAVEN_ARGS=$GALLEON_DEFAULT_ARGS
-    fi
-  else
-    if [ -z "$MAVEN_ARGS" ]; then
-        export MAVEN_ARGS="package -Popenshift -DskipTests -B"
-    fi
-    if [ -z "$GALLEON_MAVEN_ARGS" ]; then
-        export GALLEON_MAVEN_ARGS=$GALLEON_DEFAULT_ARGS
-    fi
+
+  if [ -z "$MAVEN_ARGS" ]; then
+    export MAVEN_ARGS="package -Popenshift -DskipTests -B"
+  fi
+  if [ -z "$GALLEON_MAVEN_ARGS" ]; then
+    export GALLEON_MAVEN_ARGS="install -DskipTests -B"
   fi
 
   # If MAVEN_SETTINGS specified will always add to MAVEN_ARGS
@@ -290,24 +308,22 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   fi
 
   # Server provisioning from application project
-  if [ -z "$GALLEON_BUILD" ]; then
-     if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
-       if [ -f "$GALLEON_LOCAL_PROVISIONING/pom.xml" ]; then
-         echo "Provisioning WildFly server from $GALLEON_LOCAL_PROVISIONING..."
-         mvn install $GALLEON_MAVEN_ARGS -f $GALLEON_LOCAL_PROVISIONING
+  if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
+    if [ -f "$GALLEON_LOCAL_PROVISIONING/pom.xml" ]; then
+      echo "Provisioning WildFly server from $GALLEON_LOCAL_PROVISIONING..."
+      mvn install $GALLEON_MAVEN_ARGS -f $GALLEON_LOCAL_PROVISIONING
 
-         ERR=$?
-         if [ $ERR -ne 0 ]; then
-           echo "Aborting due to error code $ERR from mvn install"
-           exit $ERR
-         fi
-         if [ -d $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly ]; then
-           replace_wildfly $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly
-         else
-           echo "Error, no wildfly server provisioned in $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly"
-           exit 1
-         fi
-       fi
+      ERR=$?
+      if [ $ERR -ne 0 ]; then
+        echo "Aborting due to error code $ERR from mvn install"
+        exit $ERR
+      fi
+      if [ -d $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly ]; then
+        replace_wildfly $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly
+      else
+        echo "Error, no wildfly server provisioned in $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly"
+        exit 1
+      fi
     fi
   fi
   popd &> /dev/null
@@ -316,49 +332,41 @@ else
   move_artifacts "." war ear rar jar
 fi
 
-if [ ! -z "$GALLEON_BUILD" ]; then
-   if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly ]; then
-     replace_wildfly $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly
-   else
-     echo "Error, no wildfly server provisioned in $LOCAL_SOURCE_DIR/$ARTIFACT_DIR/wildfly"
-     exit 1
-   fi
-else
-    # Move built artifacts (if any!) from the target/ directory
-    # (or $ARTIFACT_DIR if specified)
-    if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR ]; then
-      move_artifacts "$ARTIFACT_DIR" war ear rar jar
-    fi
-
-    if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
-      move_artifacts "deployments" war ear rar jar
-    fi
-
-    if [ -d $LOCAL_SOURCE_DIR/cfg ]; then
-      echo "Copying config files from project..."
-      cp cfg/* /wildfly/standalone/configuration
-      chgrp -R 0 /wildfly/standalone/configuration
-      chmod -R g+rw /wildfly/standalone/configuration
-      
-      cp cfg/* $CONFIG_DIR_EXTERNAL
-      chgrp -R 0 $CONFIG_DIR_EXTERNAL
-      chmod -R g+rw $CONFIG_DIR_EXTERNAL
-    fi
-
-    # this dir needs to always exist because the extended build
-    # flow expects to copy from it (even if it's empty)
-    mkdir /wildfly/provided_modules
-    if [ -d $LOCAL_SOURCE_DIR/modules ]; then
-      echo "Copying modules from project..."
-      cp -r modules/* /wildfly/provided_modules
-      chgrp -R 0 /wildfly/provided_modules
-      chmod -R g+rw /wildfly/provided_modules
-
-      cp -r modules/* $MODULE_DIR_EXTERNAL
-      chgrp -R 0 $MODULE_DIR_EXTERNAL
-      chmod -R g+rw $MODULE_DIR_EXTERNAL
-    fi
+# Move built artifacts (if any!) from the target/ directory
+# (or $ARTIFACT_DIR if specified)
+if [ -d $LOCAL_SOURCE_DIR/$ARTIFACT_DIR ]; then
+  move_artifacts "$ARTIFACT_DIR" war ear rar jar
 fi
+
+if [ -d $LOCAL_SOURCE_DIR/deployments ]; then
+  move_artifacts "deployments" war ear rar jar
+fi
+
+if [ -d $LOCAL_SOURCE_DIR/cfg ]; then
+  echo "Copying config files from project..."
+  cp cfg/* /wildfly/standalone/configuration
+  chgrp -R 0 /wildfly/standalone/configuration
+  chmod -R g+rw /wildfly/standalone/configuration
+
+  cp cfg/* $CONFIG_DIR_EXTERNAL
+  chgrp -R 0 $CONFIG_DIR_EXTERNAL
+  chmod -R g+rw $CONFIG_DIR_EXTERNAL
+fi
+
+# this dir needs to always exist because the extended build
+# flow expects to copy from it (even if it's empty)
+mkdir /wildfly/provided_modules
+if [ -d $LOCAL_SOURCE_DIR/modules ]; then
+  echo "Copying modules from project..."
+  cp -r modules/* /wildfly/provided_modules
+  chgrp -R 0 /wildfly/provided_modules
+  chmod -R g+rw /wildfly/provided_modules
+
+  cp -r modules/* $MODULE_DIR_EXTERNAL
+  chgrp -R 0 $MODULE_DIR_EXTERNAL
+  chmod -R g+rw $MODULE_DIR_EXTERNAL
+fi
+
 echo "...done"
 
 # This logic is intended to deploy the app as part of assemble
