Galleon descriptions included in builder image

diff --git a/17.0/s2i/bin/assemble b/17.0/s2i/bin/assemble
--- a/17.0/s2i/bin/assemble
+++ b/17.0/s2i/bin/assemble
@@ -136,104 +136,12 @@ function move_artifacts() {
       echo "Moving all $t artifacts from $LOCAL_SOURCE_DIR/$d directory into $DEPLOY_DIR for later deployment..."
       chgrp -fR 0 $LOCAL_SOURCE_DIR/$d/*.$t
       chmod -fR g+rw $LOCAL_SOURCE_DIR/$d/*.$t
-      cp -v $LOCAL_SOURCE_DIR/$d/*.$t $DEPLOY_DIR_EXTERNAL 2> /dev/null
       mv -v $LOCAL_SOURCE_DIR/$d/*.$t $DEPLOY_DIR 2> /dev/null
     done
   done
 }
 
-function replace_wildfly() {
-  echo "Replacing WildFly server with provisioned one"
-  srcDir=$1
-  rm -rf /wildfly/.galleon
-  rm -rf /wildfly/*
-  cp -prf $srcDir/* /wildfly
-  cp -prf $srcDir/.galleon /wildfly/.galleon
-  chown -R 1001:0 /wildfly && chmod -R ug+rwX /wildfly
-  echo "Copying WildFly server to $S2I_OUTPUT_DIR"
-  cp -r $srcDir/* $S2I_OUTPUT_DIR
-}
-
-ADMIN=admin
-PASSWORD=passw0rd_
-
-LOCAL_SOURCE_DIR=${HOME}
-mkdir -p $LOCAL_SOURCE_DIR
-
-
-# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
-# artifacts (*.war, *.jar)
-ARTIFACT_DIR=${ARTIFACT_DIR:-target}
-
-S2I_OUTPUT_DIR=/s2i-output/wildfly
-
-# Resulting WAR files will be deployed to /wildfly/standalone/deployments
-DEPLOY_DIR=/wildfly/standalone/deployments
-# To be able to chain builds, isolate artifacts in alternative location.
-DEPLOY_DIR_EXTERNAL=$S2I_OUTPUT_DIR/standalone/deployments
-CONFIG_DIR_EXTERNAL=$S2I_OUTPUT_DIR/standalone/configuration
-MODULE_DIR_EXTERNAL=$S2I_OUTPUT_DIR/provided_modules
-mkdir -p $DEPLOY_DIR
-mkdir -p $DEPLOY_DIR_EXTERNAL
-mkdir -p $CONFIG_DIR_EXTERNAL
-mkdir -p $MODULE_DIR_EXTERNAL
-
-# Embedded galleon description
-GALLEON_LOCAL_PROVISIONING=$LOCAL_SOURCE_DIR/wildfly-galleon
-
-# Copy the source for compilation
-cp -Rf /opt/s2i/destination/src/. $LOCAL_SOURCE_DIR
-chgrp -R 0 $LOCAL_SOURCE_DIR
-chmod -R g+rw $LOCAL_SOURCE_DIR
-
-if [ ! -z "$GALLEON_GIT_URL" ]; then
-   GIT="git clone --depth=1"
-   if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
-     echo "Replacing existing Galleon description in $GALLEON_LOCAL_PROVISIONING with $GALLEON_GIT_URL"
-     rm -r $GALLEON_LOCAL_PROVISIONING
-   fi
-   if [ ! -z "$GALLEON_GIT_BRANCH" ]; then
-     GIT="$GIT -b $GALLEON_GIT_BRANCH"
-   fi
-   systime=`date +%s`
-   gitDir=/tmp/galleon-repo-$systime
-   if [ -z "$GALLEON_GIT_CONTEXT_DIR" ]; then
-     GALLEON_GIT_CONTEXT_DIR=""
-   fi
-   echo "Cloning galleon description project $GIT $GALLEON_GIT_URL"
-   $GIT $GALLEON_GIT_URL $gitDir
-   GIT_ERR=$?
-   if [ $GIT_ERR -ne 0 ]; then
-     echo "Aborting due to error code $ERR from $GIT $GALLEON_URL"
-     exit $GIT_ERR
-   fi
-   mv $gitDir/$GALLEON_GIT_CONTEXT_DIR $GALLEON_LOCAL_PROVISIONING
-   rm -r $gitDir
-fi
-
-
-if [ -d $LOCAL_SOURCE_DIR/configuration ]; then
-  echo "Copying config files from project..."
-
-  if [ -f $LOCAL_SOURCE_DIR/configuration/settings.xml ]; then
-    mkdir -p $HOME/.m2
-    mv $LOCAL_SOURCE_DIR/configuration/settings.xml $HOME/.m2
-  fi
-
-  cp -v $LOCAL_SOURCE_DIR/configuration/* /wildfly/standalone/configuration/ 2> /dev/null
-fi
-
-configure_proxy
-configure_mirrors
-
-# If a pom.xml is present, this is a normal build scenario
-# so run maven.
-if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
-  # restore any maven dependencies which will be present if this is an
-  # incremental build
-  restore_saved_artifacts
-
-  pushd $LOCAL_SOURCE_DIR &> /dev/null
+function configure_maven() {
   JAVA_HOME=/etc/alternatives/java_sdk
 
   if [ -z "$MAVEN_ARGS" ]; then
@@ -295,6 +203,120 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   # so by setting the user provided MAVEN_OPTS value last, we allow the user to override any 
   # of the values we calculated above.
   MAVEN_OPTS=$JAVA_GC_OPTS $JAVA_HEAP_MAX $JAVA_CORE_LIMIT $JAVA_DIAGNOSTICS $MAVEN_OPTS
+}
+
+function replace_wildfly() {
+  echo "Replacing WildFly server with provisioned one"
+  srcDir=$1
+  rm -rf /wildfly/.galleon
+  rm -rf /wildfly/*
+  cp -prf $srcDir/* /wildfly
+  cp -prf $srcDir/.galleon /wildfly/.galleon
+  chown -R 1001:0 /wildfly && chmod -R ug+rwX /wildfly
+}
+
+function copy_server_s2i_output() {
+  S2I_OUTPUT_DIR=/s2i-output
+  mkdir -p $S2I_OUTPUT_DIR
+  echo "Copying WildFly server to $S2I_OUTPUT_DIR"
+  cp -r /wildfly $S2I_OUTPUT_DIR/wildfly  
+}
+
+function galleon_provision_server() {
+    # Embedded galleon description
+    GALLEON_LOCAL_PROVISIONING=$LOCAL_SOURCE_DIR/wildfly-galleon
+    GALLEON_ROOT_DIR=/galleon
+
+    if [ -z "$GALLEON_PROVISION_SERVER" ]; then
+      if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
+        echo "Provisioning server with Galleon description in $GALLEON_LOCAL_PROVISIONING"
+        GALLEON_DESCRIPTION_LOCATION=$GALLEON_LOCAL_PROVISIONING
+      fi
+    else
+      if [ ! -d $GALLEON_ROOT_DIR/$GALLEON_PROVISION_SERVER ]; then
+        echo "Error, $GALLEON_PROVISION_SERVER doesn't exist, can't provision a server, exiting."
+        exit 1
+      fi
+      if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
+        echo "$GALLEON_SERVER Galleon description overrides Galleon description in $GALLEON_LOCAL_PROVISIONING"
+      fi
+      GALLEON_DESCRIPTION_LOCATION=$GALLEON_ROOT_DIR/$GALLEON_PROVISION_SERVER
+    fi
+
+    if [ ! -z "$GALLEON_DESCRIPTION_LOCATION" ]; then
+      configure_maven
+      if [ -f "$GALLEON_DESCRIPTION_LOCATION/pom.xml" ]; then
+          echo "Provisioning WildFly server from $GALLEON_DESCRIPTION_LOCATION..."
+          mvn install $GALLEON_MAVEN_ARGS -f $GALLEON_DESCRIPTION_LOCATION
+
+          ERR=$?
+          if [ $ERR -ne 0 ]; then
+            echo "Aborting due to error code $ERR from mvn install"
+            exit $ERR
+          fi
+          if [ -d $GALLEON_DESCRIPTION_LOCATION/$ARTIFACT_DIR/wildfly ]; then
+            replace_wildfly $GALLEON_DESCRIPTION_LOCATION/$ARTIFACT_DIR/wildfly
+          else
+            echo "Error, no wildfly server provisioned in $GALLEON_DESCRIPTION_LOCATION/$ARTIFACT_DIR/wildfly"
+            exit 1
+          fi
+      else
+          echo "Not a valid galleon description $GALLEON_DESCRIPTION_LOCATION exiting"
+          exit 1
+      fi
+    fi  
+}
+
+ADMIN=admin
+PASSWORD=passw0rd_
+
+LOCAL_SOURCE_DIR=${HOME}
+mkdir -p $LOCAL_SOURCE_DIR
+
+
+# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
+# artifacts (*.war, *.jar)
+ARTIFACT_DIR=${ARTIFACT_DIR:-target}
+
+# Resulting WAR files will be deployed to /wildfly/standalone/deployments
+DEPLOY_DIR=/wildfly/standalone/deployments
+# To be able to chain builds, isolate artifacts in alternative location.
+mkdir -p $DEPLOY_DIR
+
+# Copy the source for compilation
+cp -Rf /opt/s2i/destination/src/. $LOCAL_SOURCE_DIR
+chgrp -R 0 $LOCAL_SOURCE_DIR
+chmod -R g+rw $LOCAL_SOURCE_DIR
+
+configure_proxy
+configure_mirrors
+
+galleon_provision_server
+
+if [ -d $LOCAL_SOURCE_DIR/configuration ]; then
+  echo "Copying config files from project..."
+
+  if [ -f $LOCAL_SOURCE_DIR/configuration/settings.xml ]; then
+    mkdir -p $HOME/.m2
+    mv $LOCAL_SOURCE_DIR/configuration/settings.xml $HOME/.m2
+  fi
+
+  cp -v $LOCAL_SOURCE_DIR/configuration/* /wildfly/standalone/configuration/ 2> /dev/null
+fi
+
+# If a pom.xml is present, this is a normal build scenario
+# so run maven.
+if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+  # restore any maven dependencies which will be present if this is an
+  # incremental build
+  restore_saved_artifacts
+
+  pushd $LOCAL_SOURCE_DIR &> /dev/null
+
+  # maven already configured if a server has been provisioned
+  if [ -z "$GALLEON_DESCRIPTION_LOCATION" ]; then
+    configure_maven
+  fi
 
   echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
@@ -307,25 +329,6 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
     exit $ERR
   fi
 
-  # Server provisioning from application project
-  if [ -d $GALLEON_LOCAL_PROVISIONING ]; then
-    if [ -f "$GALLEON_LOCAL_PROVISIONING/pom.xml" ]; then
-      echo "Provisioning WildFly server from $GALLEON_LOCAL_PROVISIONING..."
-      mvn install $GALLEON_MAVEN_ARGS -f $GALLEON_LOCAL_PROVISIONING
-
-      ERR=$?
-      if [ $ERR -ne 0 ]; then
-        echo "Aborting due to error code $ERR from mvn install"
-        exit $ERR
-      fi
-      if [ -d $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly ]; then
-        replace_wildfly $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly
-      else
-        echo "Error, no wildfly server provisioned in $GALLEON_LOCAL_PROVISIONING/$ARTIFACT_DIR/wildfly"
-        exit 1
-      fi
-    fi
-  fi
   popd &> /dev/null
 else
   echo "Moving binaries in source directory into $DEPLOY_DIR for later deployment..."
@@ -348,9 +351,6 @@ if [ -d $LOCAL_SOURCE_DIR/cfg ]; then
   chgrp -R 0 /wildfly/standalone/configuration
   chmod -R g+rw /wildfly/standalone/configuration
 
-  cp cfg/* $CONFIG_DIR_EXTERNAL
-  chgrp -R 0 $CONFIG_DIR_EXTERNAL
-  chmod -R g+rw $CONFIG_DIR_EXTERNAL
 fi
 
 # this dir needs to always exist because the extended build
@@ -362,10 +362,9 @@ if [ -d $LOCAL_SOURCE_DIR/modules ]; then
   chgrp -R 0 /wildfly/provided_modules
   chmod -R g+rw /wildfly/provided_modules
 
-  cp -r modules/* $MODULE_DIR_EXTERNAL
-  chgrp -R 0 $MODULE_DIR_EXTERNAL
-  chmod -R g+rw $MODULE_DIR_EXTERNAL
 fi
+
+copy_server_s2i_output
 
 echo "...done"
 
